version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/simple-aws-website
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: ec2-user
